#!/usr/bin/env python3
"""
agents/regulatory_watch.py
--------------------------
Regulatory Watch Agent for BioLitAgent.

Visits the configured FDA, EMA, and ICH guidance index pages, detects new or
changed guidance documents since the last recorded check, and appends
structured records to storage/pending_items.jsonl.

How change detection works
--------------------------
1. Each source page is fetched (via Playwright for JS SPAs, httpx otherwise).
2. The visible text is normalised and SHA-256 hashed.
3. If the hash differs from the stored hash for that source, the page is flagged
   as changed.  The Gemini API is then asked to identify which items are new or
   updated and to write a 2-3 sentence paraphrase of each (no verbatim copying).
4. Resulting records are appended to storage/pending_items.jsonl.
5. The state file (storage/regulatory_state.json) is updated with the new hash
   and a lightweight text snippet used as context on the next run.

Usage
-----
    python agents/regulatory_watch.py [--dry-run] [--headed] [--model MODEL]
    python agents/regulatory_watch.py --sources path/to/other_sources.json

CLI flags
---------
    --dry-run       Detect changes but do not write output or update state.
    --headed        Open a visible browser window (useful for debugging JS SPAs).
    --model MODEL   Gemini model name for extraction (default: gemini-3.8-flash).
    --sources PATH  Override the default regulatory_sources.json path.

Environment variables (from .env -- see .env.example)
-----------------------------------------------------
    GOOGLE_API_KEY  Required for LLM-based extraction and paraphrase generation.

Dependencies
------------
    pip install playwright httpx beautifulsoup4 google-genai python-dotenv
    playwright install chromium

Output schema  (one JSON object per line in pending_items.jsonl)
----------------------------------------------------------------
    {
      "id":               "<uuidv4>",
      "source_type":      "regulatory",
      "title":            "<guidance document title>",
      "agency":           "FDA | EMA | ICH",
      "url":              "<direct link to document, or null>",
      "url_unknown":      "<true if no direct URL was found on the page>",
      "publication_date": "<YYYY-MM-DD, or null>",
      "date_unknown":     "<true if no publication date was found on the page>",
      "description":      "<2-3 sentence paraphrase -- NOT verbatim regulatory text>",
      "detected_at":      "<ISO 8601 UTC timestamp>",
      "content_hash":     "<sha256 hex of the page text at detection time>",
      "source_id":        "<id from regulatory_sources.json>",
      "index_url":        "<URL of the index page that was monitored>"
    }

IMPORTANT -- copyright / compliance note
----------------------------------------
The description field must always be an original paraphrase generated by the
LLM.  Verbatim reproduction of FDA, EMA, or ICH regulatory text is explicitly
prohibited by this agent's design.  The LLM prompt enforces this constraint.
"""

from __future__ import annotations

import argparse
import asyncio
import enum
import hashlib
import json
import logging
import os
import re
import sys
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional


# -----------------------------------------------------------------------------
# Extraction result types
# -----------------------------------------------------------------------------


class ExtractionStatus(str, enum.Enum):
    """
    Unambiguous outcome codes returned by _extract_items_via_llm.

    SKIPPED_API_ERROR  - the Gemini API failed after all retries were exhausted.
    SKIPPED_PARSE_ERROR - the API responded but the output could not be parsed as JSON.
    NO_NEW_ITEMS        - the API responded and was parsed; genuinely no new items found.
    ITEMS_FOUND         - one or more new/changed items were successfully extracted.
    NO_CHANGE           - page hash matched; LLM was never called (set by _watch_source).
    FETCH_ERROR         - page could not be fetched; LLM was never called.
    """

    SKIPPED_API_ERROR   = "SKIPPED_API_ERROR"
    SKIPPED_QUOTA_EXHAUSTED = "SKIPPED_QUOTA_EXHAUSTED"
    SKIPPED_PARSE_ERROR = "SKIPPED_PARSE_ERROR"
    NO_NEW_ITEMS        = "NO_NEW_ITEMS"
    ITEMS_FOUND         = "ITEMS_FOUND"
    NO_CHANGE           = "NO_CHANGE"
    FETCH_ERROR         = "FETCH_ERROR"
    CACHE_HIT           = "CACHE_HIT"


@dataclass
class ExtractionResult:
    """Returned by _extract_items_via_llm (and propagated by _watch_source)."""

    status: ExtractionStatus
    items: list[dict[str, Any]] = field(default_factory=list)
    # Human-readable detail for log / summary (error message, item count, etc.)
    detail: str = ""

# -- Optional dependency: python-dotenv --------------------------------------
try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass  # .env loading is optional; values may be injected by the orchestrator

# -- Optional dependency: Playwright -----------------------------------------
try:
    from playwright.async_api import (
        Browser,
        BrowserContext,
        Page,
        async_playwright,
    )
    from playwright.async_api import TimeoutError as PWTimeoutError

    _PLAYWRIGHT_AVAILABLE = True
except ImportError:
    _PLAYWRIGHT_AVAILABLE = False

# -- Optional dependency: httpx (lightweight fetcher for non-JS pages) --------
try:
    import httpx

    _HTTPX_AVAILABLE = True
except ImportError:
    _HTTPX_AVAILABLE = False

# -- Optional dependency: BeautifulSoup ---------------------------------------
try:
    from bs4 import BeautifulSoup

    _BS4_AVAILABLE = True
except ImportError:
    _BS4_AVAILABLE = False

# -- Optional dependency: google-genai ----------------------------------------
try:
    import google.genai as genai
    from google.genai import types as genai_types

    _GENAI_AVAILABLE = True
except ImportError:
    _GENAI_AVAILABLE = False

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------

# All paths are resolved relative to the project root (parent of agents/).
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))
if str(_ROOT.parent) not in sys.path:
    sys.path.insert(0, str(_ROOT.parent))

_DEFAULT_SOURCES = _ROOT / "config" / "regulatory_sources.json"
_STATE_FILE = _ROOT / "storage" / "regulatory_state.json"
_OUTPUT_FILE = _ROOT / "storage" / "pending_items.jsonl"
_DRY_RUN_CACHE_FILE = _ROOT / "storage" / "dry_run_llm_cache.json"

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s -- %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
    stream=sys.stdout,
)
log = logging.getLogger("regulatory_watch")

# -----------------------------------------------------------------------------
# LLM client (lazy initialisation)
# -----------------------------------------------------------------------------

try:
    from biolitagent.config.model_config import DEFAULT_MODEL
except ImportError:
    try:
        from config.model_config import DEFAULT_MODEL
    except ImportError:
        DEFAULT_MODEL = "gemini-2.5-flash"

_DEFAULT_MODEL = DEFAULT_MODEL
_llm_client: Optional[Any] = None
_llm_model: str = _DEFAULT_MODEL
_daily_quota_exhausted: bool = False
_preflight_checked: bool = False

try:
    from biolitagent.config.quota_guard import (
        check_preflight_gate,
        is_daily_exhaustion,
        parse_quota_failure,
        record_call,
    )
except ImportError:
    try:
        from config.quota_guard import (
            check_preflight_gate,
            is_daily_exhaustion,
            parse_quota_failure,
            record_call,
        )
    except ImportError:
        def check_preflight_gate(estimated_calls: int, agent_name: str) -> bool: return True
        def is_daily_exhaustion(quota_id: Optional[str], exc_str: str = "") -> bool: return False
        def parse_quota_failure(exc: Exception) -> tuple[bool, Optional[str], Optional[str]]: return False, None, None
        def record_call(agent_name: str) -> int: return 0


def _get_llm_client() -> Any:
    """Return a cached google.genai Client, initialising it on first call."""
    global _llm_client
    if _llm_client is not None:
        return _llm_client
    if not _GENAI_AVAILABLE:
        raise RuntimeError(
            "google-genai is not installed.\n"
            "  pip install google-genai"
        )
    api_key = os.environ.get("GOOGLE_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError(
            "GOOGLE_API_KEY environment variable is not set.\n"
            "  Copy .env.example -> .env and add your key."
        )
    _llm_client = genai.Client(api_key=api_key)
    log.debug("Gemini client initialised (model: %s).", _llm_model)
    return _llm_client


# -----------------------------------------------------------------------------
# State helpers
# -----------------------------------------------------------------------------


def load_state() -> dict[str, Any]:
    """Load the persisted per-source hash state from disk."""
    if _STATE_FILE.exists():
        try:
            return json.loads(_STATE_FILE.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            log.warning(
                "regulatory_state.json is corrupt -- starting from a clean state. "
                "All enabled sources will be treated as first-visit."
            )
    return {}


def save_state(state: dict[str, Any]) -> None:
    """Persist the updated per-source hash state to disk."""
    _STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    _STATE_FILE.write_text(
        json.dumps(state, indent=2, ensure_ascii=False, sort_keys=True),
        encoding="utf-8",
    )
    log.debug("State saved -> %s", _STATE_FILE)


# -----------------------------------------------------------------------------
# Dry-run LLM response cache helpers
# -----------------------------------------------------------------------------


def load_dry_run_cache() -> dict[str, Any]:
    """Load the dry-run LLM response cache from storage/dry_run_llm_cache.json."""
    if _DRY_RUN_CACHE_FILE.exists():
        try:
            return json.loads(_DRY_RUN_CACHE_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            log.warning("Could not read dry_run_llm_cache.json: %s", exc)
    return {}


def save_dry_run_cache(cache: dict[str, Any]) -> None:
    """Persist the dry-run LLM response cache to storage/dry_run_llm_cache.json."""
    try:
        _DRY_RUN_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        _DRY_RUN_CACHE_FILE.write_text(
            json.dumps(cache, indent=2, ensure_ascii=False, sort_keys=True),
            encoding="utf-8",
        )
        log.debug("Dry-run cache saved -> %s", _DRY_RUN_CACHE_FILE)
    except OSError as exc:
        log.warning("Could not save dry-run cache to %s: %s", _DRY_RUN_CACHE_FILE, exc)


def get_cached_llm_response(content_hash: str) -> Optional[ExtractionResult]:
    """Return a cached ExtractionResult for content_hash if present, or None."""
    cache = load_dry_run_cache()
    entry = cache.get(content_hash)
    if not entry:
        return None

    if isinstance(entry, list):
        status = ExtractionStatus.ITEMS_FOUND if entry else ExtractionStatus.NO_NEW_ITEMS
        detail = f"{len(entry)} item(s) from cache."
        return ExtractionResult(status=status, items=entry, detail=detail)

    if isinstance(entry, dict):
        status_val = entry.get("status")
        try:
            status = ExtractionStatus(status_val) if status_val else None
        except (ValueError, TypeError):
            status = None

        items = entry.get("items", [])
        if status is None:
            status = ExtractionStatus.ITEMS_FOUND if items else ExtractionStatus.NO_NEW_ITEMS
        detail = entry.get("detail", f"{len(items)} item(s) from cache.")
        return ExtractionResult(status=status, items=items, detail=detail)

    return None


def cache_llm_response(
    content_hash: str,
    source_id: str,
    result: ExtractionResult,
) -> None:
    """Store a successful real API call result in the dry-run cache."""
    # Only cache successful API extractions (ITEMS_FOUND or NO_NEW_ITEMS)
    if result.status not in (ExtractionStatus.ITEMS_FOUND, ExtractionStatus.NO_NEW_ITEMS):
        return
    cache = load_dry_run_cache()
    cache[content_hash] = {
        "source_id": source_id,
        "status": result.status.value,
        "items": result.items,
        "detail": result.detail,
        "cached_at": datetime.now(timezone.utc).isoformat(),
    }
    save_dry_run_cache(cache)


def sha256_of(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# -----------------------------------------------------------------------------
# HTTP / browser fetch helpers
# -----------------------------------------------------------------------------

# A minimal User-Agent that identifies the bot and provides a contact point.
_UA = (
    "Mozilla/5.0 (compatible; BioLitAgent/regulatory-watch; "
    "+https://github.com/your-org/biolitagent)"
)

# Maximum characters passed to the LLM to stay well within context limits.
_MAX_LLM_CHARS = 14_000

# Characters retained as "text snippet" in the state file for diff context.
_STATE_SNIPPET_CHARS = 3_000


async def _fetch_static(url: str, timeout_s: int = 30) -> str:
    """Fetch a non-JS page with httpx and return the raw HTML."""
    if not _HTTPX_AVAILABLE:
        raise RuntimeError("httpx is not installed.  pip install httpx")
    async with httpx.AsyncClient(
        headers={"User-Agent": _UA},
        follow_redirects=True,
        timeout=timeout_s,
    ) as client:
        response = await client.get(url)
        response.raise_for_status()
        return response.text


async def _fetch_js_rendered(
    page: Page,
    url: str,
    wait_selector: Optional[str],
    timeout_ms: int = 45_000,
) -> str:
    """Navigate Playwright to *url*, wait for content to stabilise, return HTML."""
    try:
        await page.goto(url, wait_until="networkidle", timeout=timeout_ms)
    except PWTimeoutError:
        log.warning("networkidle timed out for %s -- falling back to domcontentloaded", url)
        await page.goto(url, wait_until="domcontentloaded", timeout=timeout_ms)

    if wait_selector:
        try:
            await page.wait_for_selector(wait_selector, timeout=timeout_ms)
        except PWTimeoutError:
            log.warning("Selector '%s' not found on %s -- proceeding anyway.", wait_selector, url)

    return await page.content()


def _extract_visible_text(html: str) -> str:
    """
    Strip navigation chrome and return clean, deduplicated visible text.
    Falls back to simple regex stripping if BeautifulSoup is unavailable.
    """
    if _BS4_AVAILABLE:
        soup = BeautifulSoup(html, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "header", "noscript"]):
            tag.decompose()
        raw = soup.get_text(separator="\n")
    else:
        # Minimal fallback: strip HTML tags
        raw = re.sub(r"<[^>]+>", " ", html)

    lines = [ln.strip() for ln in raw.splitlines()]
    return "\n".join(ln for ln in lines if ln)


# -----------------------------------------------------------------------------
# LLM extraction
# -----------------------------------------------------------------------------

_EXTRACT_PROMPT = """\
You are an expert regulatory affairs scientist helping to monitor {agency} guidance publications.

The text below is the CURRENT content of the guidance index page at:
  {url}

{diff_context}

YOUR TASK
---------
1. Identify guidance documents that appear to be NEW or RECENTLY UPDATED on this page
   compared to the previous snapshot (if one exists).
2. For each such document, return ALL of the following fields:

     title            - the exact title of the guidance document.

     publication_date - the publication or revision date in YYYY-MM-DD format.
                        If the date is visible but only partially (e.g. "June 2024"),
                        convert it to the best available precision (e.g. "2024-06-01").
                        If NO date is visible anywhere on the page for this item, set
                        this field to null AND set "date_unknown": true.

     url              - the full absolute URL (https://...) linking directly to the
                        guidance document PDF or detail page, as found in the page text.
                        If NO direct link is visible for this item, set this field to
                        null AND set "url_unknown": true.

     description      - 2 to 3 sentences, IN YOUR OWN WORDS, describing what this
                        guidance covers and why it is noteworthy.
                        DO NOT copy verbatim text from the page.
                        DO NOT quote regulatory document language directly.

     date_unknown     - (boolean) true if and only if publication_date could not be
                        determined from the page. Omit or set false if a date was found.

     url_unknown      - (boolean) true if and only if no direct document URL could be
                        found on the page. Omit or set false if a URL was found.

3. If no new or changed items are identifiable, return an empty JSON array.

OUTPUT FORMAT
-------------
Return ONLY a valid JSON array -- no markdown fences, no prose before or after:
[
  {{
    "title": "...",
    "publication_date": "YYYY-MM-DD or null",
    "date_unknown": false,
    "url": "https://... or null",
    "url_unknown": false,
    "description": "..."
  }}
]

PAGE TEXT (up to {max_chars} characters):
{page_text}
"""

# Transient HTTP status codes that warrant a retry against the Gemini API.
_RETRYABLE_STATUS_CODES = {429, 503}
# Maximum number of retry attempts for transient API errors.
_MAX_LLM_RETRIES = 3
# Base backoff in seconds; actual delay = _BACKOFF_BASE * 2^attempt (2s, 4s, 8s).
_BACKOFF_BASE = 2.0


async def _extract_items_via_llm(
    agency: str,
    index_url: str,
    current_text: str,
    previous_text: Optional[str],
) -> ExtractionResult:
    """
    Ask Gemini to identify new / changed guidance items and return an ExtractionResult.

    Structured JSON output
    ----------------------
    The API call uses response_mime_type="application/json" (and response_schema
    when available) so the model is constrained to emit valid JSON without any
    wrapping prose.  Fence-stripping is applied as a defense-in-depth fallback
    in case the model or an intermediate proxy re-wraps the output.

    Retry behaviour
    ---------------
    Retries up to _MAX_LLM_RETRIES times on transient 503 / 429 errors with
    exponential backoff (2 s, 4 s, 8 s).

    Return values
    -------------
    ExtractionResult.status is always one of:
      SKIPPED_API_ERROR   - Gemini API failed after all retries.
      SKIPPED_PARSE_ERROR - API responded; output was not valid JSON / wrong shape.
      NO_NEW_ITEMS        - Parsed successfully; model found no new items.
      ITEMS_FOUND         - Parsed successfully; one or more items returned.
    """
    client = _get_llm_client()

    if previous_text:
        diff_context = (
            "A PREVIOUS SNAPSHOT of this page exists. "
            "Focus exclusively on items that are NEW or REVISED since the last run. "
            "Ignore items that appeared in the previous snapshot unchanged."
        )
    else:
        diff_context = (
            "NO PREVIOUS SNAPSHOT exists -- this is the first visit to this source. "
            "Return up to the 5 most recently published or updated items visible on the page."
        )

    prompt = _EXTRACT_PROMPT.format(
        agency=agency,
        url=index_url,
        diff_context=diff_context,
        max_chars=_MAX_LLM_CHARS,
        page_text=current_text[:_MAX_LLM_CHARS],
    )

    # -- Build the GenerateContentConfig with structured JSON output -----------
    # response_mime_type constrains the model to emit a bare JSON document.
    # response_schema (a JSON Schema object) further constrains the shape.
    # Both are supported by Gemini 1.5+ / 2.0+; we guard against SDK versions
    # that don't yet expose response_schema via hasattr inspection.
    _item_schema = {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "title":            {"type": "string"},
                "publication_date": {"type": ["string", "null"]},
                "date_unknown":     {"type": "boolean"},
                "url":              {"type": ["string", "null"]},
                "url_unknown":      {"type": "boolean"},
                "description":      {"type": "string"},
            },
            "required": ["title", "description"],
        },
    }

    config_kwargs: dict[str, Any] = {
        "temperature": 0.1,
        "max_output_tokens": 8192,
        "response_mime_type": "application/json",
    }
    # response_schema was added in google-genai >= 0.7; skip gracefully if absent.
    if hasattr(genai_types.GenerateContentConfig, "response_schema"):
        config_kwargs["response_schema"] = _item_schema

    gen_config = genai_types.GenerateContentConfig(**config_kwargs)

    # -- API call with retry-backoff -------------------------------------------
    global _daily_quota_exhausted
    if _daily_quota_exhausted:
        return ExtractionResult(
            status=ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED,
            detail="Daily Gemini quota exhausted.",
        )

    last_exc: Optional[Exception] = None
    response = None

    for attempt in range(_MAX_LLM_RETRIES + 1):
        try:
            record_call("regulatory_watch")
            response = client.models.generate_content(
                model=_llm_model,
                contents=prompt,
                config=gen_config,
            )
            break  # success -- exit retry loop

        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            exc_str = str(exc)

            is_quota, quota_id, retry_delay = parse_quota_failure(exc)
            if is_quota and is_daily_exhaustion(quota_id, exc_str):
                _daily_quota_exhausted = True
                msg = (
                    f"Daily Gemini quota exhausted (quotaId: {quota_id or 'PerDay'}): {exc}"
                )
                log.warning("  -> [SKIPPED_QUOTA_EXHAUSTED] %s -- %s", index_url, msg)
                return ExtractionResult(
                    status=ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED,
                    detail=msg,
                )

            # Detect retryable status codes embedded in the exception message.
            is_retryable = any(
                f"{code}" in exc_str
                or f"HTTP {code}" in exc_str
                or f"status {code}" in exc_str
                for code in _RETRYABLE_STATUS_CODES
            )

            if is_retryable and attempt < _MAX_LLM_RETRIES:
                delay = _BACKOFF_BASE * (2 ** attempt)  # 2s, 4s, 8s
                log.warning(
                    "  -> [RETRY %d/%d] Transient Gemini API error for %s "
                    "(retrying in %.0fs): %s",
                    attempt + 1,
                    _MAX_LLM_RETRIES,
                    index_url,
                    delay,
                    exc,
                )
                await asyncio.sleep(delay)
            else:
                # Non-retryable, or this was the last allowed attempt.
                msg = (
                    f"Gemini API failed after {attempt + 1}/{_MAX_LLM_RETRIES} "
                    f"attempt(s): {exc}"
                )
                log.error("  -> [SKIPPED_API_ERROR] %s -- %s", index_url, msg)
                return ExtractionResult(
                    status=ExtractionStatus.SKIPPED_API_ERROR,
                    detail=msg,
                )

    if response is None:
        # for-else: loop ran to completion without a successful break.
        msg = (
            f"Gemini API failed after {_MAX_LLM_RETRIES}/{_MAX_LLM_RETRIES} "
            f"attempt(s): {last_exc}"
        )
        log.error("  -> [SKIPPED_API_ERROR] %s -- %s", index_url, msg)
        return ExtractionResult(
            status=ExtractionStatus.SKIPPED_API_ERROR,
            detail=msg,
        )

    # -- Parse the response ----------------------------------------------------
    raw = (response.text or "").strip()

    # Defense-in-depth: strip markdown fences in case a proxy re-wraps output.
    # Pattern covers ```json\n...\n``` and ``` \n...\n ```.
    fence_match = re.match(r"^```(?:json)?\s*\n?(.*?)\n?```\s*$", raw, re.DOTALL)
    if fence_match:
        raw = fence_match.group(1).strip()

    # An empty string or bare "[]" from the model means no items found.
    if not raw or raw == "[]":
        log.info("  -> [NO_NEW_ITEMS] %s -- model returned an empty result.", index_url)
        return ExtractionResult(
            status=ExtractionStatus.NO_NEW_ITEMS,
            detail="Model returned empty JSON array.",
        )

    try:
        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            raise ValueError(f"Expected JSON array, got {type(parsed).__name__}")
    except (json.JSONDecodeError, ValueError) as exc:
        msg = f"{type(exc).__name__}: {exc}"
        log.error(
            "  -> [SKIPPED_PARSE_ERROR] %s -- could not parse LLM output as JSON.\n"
            "    Error: %s\n"
            "    Raw output (first 500 chars): %.500s",
            index_url,
            msg,
            raw,
        )
        return ExtractionResult(
            status=ExtractionStatus.SKIPPED_PARSE_ERROR,
            detail=msg,
        )

    if not parsed:
        log.info("  -> [NO_NEW_ITEMS] %s -- model found no new or changed items.", index_url)
        return ExtractionResult(
            status=ExtractionStatus.NO_NEW_ITEMS,
            detail="Parsed successfully; zero items returned.",
        )

    log.info("  -> [ITEMS_FOUND] %s -- %d item(s) extracted.", index_url, len(parsed))
    return ExtractionResult(
        status=ExtractionStatus.ITEMS_FOUND,
        items=parsed,
        detail=f"{len(parsed)} item(s) extracted.",
    )


# -----------------------------------------------------------------------------
# Output helpers
# -----------------------------------------------------------------------------


def _build_record(
    source: dict[str, Any],
    item: dict[str, Any],
    content_hash: str,
) -> dict[str, Any]:
    """Assemble a pending_items.jsonl record from a source config and an extracted item."""
    return {
        "id": str(uuid.uuid4()),
        "source_type": "regulatory",
        "title": (item.get("title") or "").strip() or "Untitled guidance",
        "agency": source.get("agency", "Unknown"),
        "url": item.get("url"),
        # True when the LLM explicitly could not find a URL on the page.
        "url_unknown": bool(item.get("url_unknown", False)),
        "publication_date": item.get("publication_date"),
        # True when the LLM explicitly could not find a publication date on the page.
        "date_unknown": bool(item.get("date_unknown", False)),
        # The description must be LLM-generated; never verbatim regulatory text.
        "description": (item.get("description") or "").strip(),
        "synthesis_method": item.get("synthesis_method", "gemini"),
        "detected_at": datetime.now(timezone.utc).isoformat(),
        "content_hash": content_hash,
        "source_id": source.get("id", ""),
        "index_url": source.get("url", ""),
        "model_name": _llm_model if item.get("synthesis_method", "gemini") == "gemini" else None,
        "config_versions": {"taxonomy_version": "1.1", "queries_version": "1.1"},
    }


def _append_record(record: dict[str, Any], dry_run: bool) -> None:
    """Append one JSONL record to pending_items.jsonl (or log it in dry-run mode)."""
    line = json.dumps(record, ensure_ascii=False)
    if dry_run:
        log.info("[DRY RUN] Would append -> %s", line)
        return
    _OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with _OUTPUT_FILE.open("a", encoding="utf-8") as fh:
        fh.write(line + "\n")
    log.info("  [OK] Appended: %s", record["title"])


# -----------------------------------------------------------------------------
# Per-source watch logic
# -----------------------------------------------------------------------------


async def _watch_source(
    source: dict[str, Any],
    state: dict[str, Any],
    playwright_page: Optional[Page],
    dry_run: bool,
) -> ExtractionStatus:
    """
    Process one regulatory source: fetch, compare, extract, emit.

    Returns an ExtractionStatus so the caller (run()) can accumulate a
    per-source summary without any failure mode being silently swallowed.

    *playwright_page* must be a live Playwright Page if source['requires_js']
    is true; it may be None for static pages.
    """
    source_id = source["id"]
    agency = source.get("agency", "Unknown")
    index_url = source["url"]
    requires_js = source.get("requires_js", False)
    wait_selector = source.get("wait_selector")

    log.info("-- %-5s | %s", agency, index_url)

    # -- Fetch ----------------------------------------------------------------
    try:
        if requires_js:
            if playwright_page is None:
                raise RuntimeError(
                    f"Source '{source_id}' requires JS rendering but no "
                    "Playwright page was provided."
                )
            html = await _fetch_js_rendered(playwright_page, index_url, wait_selector)
        else:
            html = await _fetch_static(index_url)
    except Exception as exc:
        log.error("  -> [FETCH_ERROR] %s: %s", index_url, exc)
        return ExtractionStatus.FETCH_ERROR

    # -- Normalise and hash ---------------------------------------------------
    current_text = _extract_visible_text(html)
    current_hash = sha256_of(current_text)

    previous_entry = state.get(source_id, {})
    previous_hash: Optional[str] = previous_entry.get("hash")
    previous_text: Optional[str] = previous_entry.get("text_snippet")

    if _daily_quota_exhausted:
        log.warning("  -> [SKIPPED_QUOTA_EXHAUSTED] %s -- Daily Gemini quota exhausted; skipping without calling API.", index_url)
        return ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED

    if current_hash == previous_hash:
        log.info("  -> [NO_CHANGE] Hash match (%s...) -- skipping LLM call.", current_hash[:12])
        return ExtractionStatus.NO_CHANGE

    log.info(
        "  -> Change detected (prev=%s... -> curr=%s...) -- running LLM extraction.",
        (previous_hash or "none")[:12],
        current_hash[:12],
    )

    # -- LLM extraction -------------------------------------------------------
    cached_result: Optional[ExtractionResult] = None
    is_cache_hit: bool = False
    if dry_run:
        cached_result = get_cached_llm_response(current_hash)

    if cached_result is not None:
        log.info("[DRY RUN] Cache hit for %s -- skipping LLM call", current_hash)
        log.info("[CACHE_HIT] Using cached extraction for %s, skipping Gemini call", source_id)
        result = cached_result
        is_cache_hit = True
    else:
        global _preflight_checked
        if not _preflight_checked:
            if not check_preflight_gate(1, "regulatory_watch"):
                log.info("[QUOTA_GUARD] Pre-flight gate aborted by reviewer -- skipping extraction.")
                return ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED
            _preflight_checked = True

        result = await _extract_items_via_llm(
            agency=agency,
            index_url=index_url,
            current_text=current_text,
            previous_text=previous_text,
        )
        # Only write to this cache after a successful real API call (dry-run only)
        if dry_run and result.status in (ExtractionStatus.ITEMS_FOUND, ExtractionStatus.NO_NEW_ITEMS):
            cache_llm_response(
                content_hash=current_hash,
                source_id=source_id,
                result=result,
            )

    if result.status == ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED:
        return ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED

    # Emit pending records only on success.
    if result.status == ExtractionStatus.ITEMS_FOUND:
        for item in result.items:
            record = _build_record(source, item, content_hash=current_hash)
            _append_record(record, dry_run=dry_run)

    # -- Update state entry ---------------------------------------------------
    # Update state for any outcome where we actually fetched and hashed the page,
    # even if LLM extraction failed -- so that a transient API error doesn't cause
    # the same changed page to be re-submitted on every subsequent run.
    # Exception: do NOT update state on FETCH_ERROR (handled above by early return),
    # NO_CHANGE (state already current), or SKIPPED_QUOTA_EXHAUSTED (retry next day).
    state[source_id] = {
        "hash": current_hash,
        "last_checked": datetime.now(timezone.utc).isoformat(),
        # Small snippet for LLM diff context on the next run.
        "text_snippet": current_text[:_STATE_SNIPPET_CHARS],
        # Persist the last extraction status for debugging.
        "last_extraction_status": result.status.value,
    }

    return ExtractionStatus.CACHE_HIT if is_cache_hit else result.status



# -----------------------------------------------------------------------------
# Run summary
# -----------------------------------------------------------------------------

# Status display metadata: (label, log-level method name, short description)
_STATUS_META: dict[ExtractionStatus, tuple[str, str, str]] = {
    ExtractionStatus.ITEMS_FOUND:             ("[OK] ITEMS_FOUND",             "info",    "new items extracted and written"),
    ExtractionStatus.CACHE_HIT:               ("[CACHE_HIT] CACHE_HIT",         "info",    "used cached LLM extraction; LLM call skipped"),
    ExtractionStatus.NO_NEW_ITEMS:            ("[OK]  NO_NEW_ITEMS",            "info",    "checked; no new items found"),
    ExtractionStatus.NO_CHANGE:               ("-  NO_CHANGE",               "info",    "page hash unchanged; LLM skipped"),
    ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED: ("[!]  SKIPPED_QUOTA_EXHAUSTED", "warning", "daily Gemini quota exhausted; skipped without calls"),
    ExtractionStatus.SKIPPED_PARSE_ERROR:     ("[!]  SKIPPED_PARSE_ERROR",     "warning", "API responded but output was unparseable"),
    ExtractionStatus.FETCH_ERROR:             ("[X]  FETCH_ERROR",             "error",   "page could not be fetched"),
    ExtractionStatus.SKIPPED_API_ERROR:       ("[X]  SKIPPED_API_ERROR",       "error",   "Gemini API failed after all retries"),
}


def _print_run_summary(summary: dict[str, ExtractionStatus]) -> None:
    """
    Print a per-source status table and a count breakdown at end-of-run.

    Each source gets exactly one line so that:
      * A source that was checked and found clean is clearly labelled NO_NEW_ITEMS
        or NO_CHANGE, not collapsed into the same output as an errored source.
      * SKIPPED_API_ERROR, SKIPPED_PARSE_ERROR, and FETCH_ERROR are visually
        distinct and always appear explicitly in the log.
    """
    if not summary:
        log.info("Run summary: no sources were processed.")
        return

    col_w = max(len(sid) for sid in summary) + 2
    sep = "-" * (col_w + 30)

    log.info("")
    log.info("+%s+", sep)
    log.info("|  RUN SUMMARY -- %d source(s) processed%s|",
             len(summary), " " * (col_w + 30 - 16 - len(str(len(summary))) - 20))
    log.info("+%s+", sep)

    counts: dict[ExtractionStatus, int] = {}
    for source_id, status in summary.items():
        meta = _STATUS_META.get(status, (status.value, "info", ""))
        label, level, _ = meta
        counts[status] = counts.get(status, 0) + 1
        getattr(log, level)("|  %-*s  %s", col_w, source_id, label)

    log.info("+%s+", sep)
    log.info("|  Counts:", )
    for status, count in sorted(counts.items(), key=lambda kv: kv[0].value):
        label = _STATUS_META.get(status, (status.value, "info", ""))[0]
        log.info("|    %s: %d", label, count)
    log.info("+%s+", sep)
    log.info("")


async def run(args: argparse.Namespace) -> int:
    """
    Orchestrate the full regulatory watch cycle.
    Returns 0 on success, 1 on fatal error.
    """
    # -- Dependency checks ----------------------------------------------------
    missing: list[str] = []
    if not _BS4_AVAILABLE:
        missing.append("beautifulsoup4")
    if not _HTTPX_AVAILABLE:
        missing.append("httpx")
    if not _PLAYWRIGHT_AVAILABLE:
        missing.append("playwright  (+ run: playwright install chromium)")
    if not _GENAI_AVAILABLE:
        missing.append("google-genai")
    if missing:
        log.error(
            "Missing required dependencies:\n  pip install %s",
            " ".join(m for m in missing if "playwright install" not in m),
        )
        return 1

    # -- Load sources ---------------------------------------------------------
    sources_path = Path(args.sources)
    if not sources_path.exists():
        log.error("Sources file not found: %s", sources_path)
        return 1

    all_sources: list[dict[str, Any]] = json.loads(
        sources_path.read_text(encoding="utf-8")
    ).get("sources", [])
    enabled = [s for s in all_sources if s.get("enabled", True)]
    js_needed = any(s.get("requires_js", False) for s in enabled)

    log.info(
        "Loaded %d source(s) -- %d enabled (%d require JS rendering).",
        len(all_sources),
        len(enabled),
        sum(1 for s in enabled if s.get("requires_js", False)),
    )

    if not enabled:
        log.warning("No enabled sources found -- nothing to do.")
        return 0

    # -- Load persisted state -------------------------------------------------
    state: dict[str, Any] = load_state()

    # -- Pre-flight gate check (Part C) ---------------------------------------
    global _preflight_checked
    if not _STATE_FILE.exists() or not state:
        estimated_calls = len(enabled)
        if not check_preflight_gate(estimated_calls, "regulatory_watch"):
            log.info("[QUOTA_GUARD] Pre-flight gate aborted by reviewer -- 0 API calls made.")
            return 0
        _preflight_checked = True

    # -- Per-source status accumulator (for the end-of-run summary) -----------
    # Maps source_id -> ExtractionStatus  (one entry per enabled source).
    run_summary: dict[str, ExtractionStatus] = {}

    # -- Run with Playwright context ------------------------------------------
    async with async_playwright() as pw:
        browser: Optional[Browser] = None
        playwright_page: Optional[Page] = None

        if js_needed:
            browser = await pw.chromium.launch(headless=not args.headed)
            context: BrowserContext = await browser.new_context(
                user_agent=_UA,
                viewport={"width": 1280, "height": 900},
                # Ignore HTTPS errors on government sites with odd cert chains
                ignore_https_errors=True,
            )
            playwright_page = await context.new_page()
            log.info("Playwright browser launched (headless=%s).", not args.headed)

        try:
            for idx, source in enumerate(enabled):
                source_id = source.get("id", "<unknown>")
                if _daily_quota_exhausted:
                    rem_sources = enabled[idx:]
                    log.warning(
                        "Daily Gemini quota exhausted -- skipping %d remaining source(s)/item(s) without further attempts.",
                        len(rem_sources),
                    )
                    for rem in rem_sources:
                        run_summary[rem.get("id", "<unknown>")] = ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED
                    break

                try:
                    status = await _watch_source(
                        source=source,
                        state=state,
                        playwright_page=playwright_page,
                        dry_run=args.dry_run,
                    )
                    run_summary[source_id] = status
                    if _daily_quota_exhausted:
                        rem_sources = enabled[idx + 1:]
                        if rem_sources:
                            log.warning(
                                "Daily Gemini quota exhausted -- skipping %d remaining source(s)/item(s) without further attempts.",
                                len(rem_sources),
                            )
                            for rem in rem_sources:
                                run_summary[rem.get("id", "<unknown>")] = ExtractionStatus.SKIPPED_QUOTA_EXHAUSTED
                        break
                except Exception as exc:  # noqa: BLE001
                    # An unexpected exception that escaped _watch_source's own
                    # error handling -- record it so it appears in the summary.
                    log.error(
                        "  [SKIPPED_API_ERROR] Source '%s' raised an unexpected exception: "
                        "%s: %s",
                        source_id,
                        type(exc).__name__,
                        exc,
                        exc_info=args.verbose,  # full traceback only with --verbose
                    )
                    run_summary[source_id] = ExtractionStatus.SKIPPED_API_ERROR
                delay = source.get("delay_seconds", 4)
                log.debug("Polite delay: %ss", delay)
                await asyncio.sleep(delay)
        finally:
            if browser is not None:
                await browser.close()

    # -- Persist updated state ------------------------------------------------
    if args.dry_run:
        log.info("[DRY RUN] State NOT saved (pass without --dry-run to persist).")
    else:
        save_state(state)

    # -- End-of-run summary ---------------------------------------------------
    # Print one line per source so skipped / broken sources are never silently
    # indistinguishable from sources that were checked and found clean.
    _print_run_summary(run_summary)

    # Signal a non-zero exit if any source hit a hard error.
    error_statuses = {ExtractionStatus.SKIPPED_API_ERROR, ExtractionStatus.FETCH_ERROR}
    had_errors = any(s in error_statuses for s in run_summary.values())
    return 1 if had_errors else 0




# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="regulatory_watch",
        description=(
            "BioLitAgent Regulatory Watch Agent -- detects new/changed FDA, EMA, "
            "and ICH guidance documents and appends structured records to "
            "storage/pending_items.jsonl."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--sources",
        metavar="PATH",
        default=str(_DEFAULT_SOURCES),
        help="Path to regulatory_sources.json.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Detect changes but do not write output files or update state.",
    )
    parser.add_argument(
        "--headed",
        action="store_true",
        help="Launch a visible browser window (useful for debugging JS SPAs).",
    )
    parser.add_argument(
        "--model",
        metavar="MODEL",
        default=_DEFAULT_MODEL,
        help="Gemini model for extraction and paraphrase generation.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable DEBUG-level log output.",
    )
    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Push model choice into module-level variable used by _get_llm_client.
    global _llm_model
    _llm_model = args.model

    exit_code = asyncio.run(run(args))
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
